# Float calculator, fullscreen RetroArch
windowrule = float, class:org.gnome.Calculator
windowrule = float, class:org.gnome.DiskUtility

windowrule = float, class:Bitwarden

# Clipboard manager
windowrule = float, class:(clipse-gui)
windowrule = size 622 652, class:(clipse-gui)
windowrule = stayfocused, class:(clipse-gui)
# windowrule = center, class:org.gnome.Calculator, title:Steam
