# Extra autostart processes
# exec-once = uwsm app -- my-service


# set mouse on workspace 1
exec-once = hyprctl dispatch workspace 5
exec-once = hyprctl dispatch focusmonitor 0
exec-once = hyprctl dispatch workspace 1

# game tags

windowrule = tag +games, class:^(gamescope)$

windowrule = tag +games, class:^(steam_proton)$

windowrule = tag +games, class:^(retroarch)$

windowrule = tag +games, title:^(Minecraft.*)$

windowrule = tag +games, class:^(.*.exe), title:^(.+), xwayland:^(0)$

windowrule = tag +games, xdgTag:^(proton-game)$

windowrule = tag +games, class:^(steam_app_\d+)$

windowrule = noblur, tag:games*

windowrule = fullscreen, tag:games*

windowrule = workspace 4, tag:games*

exec-once = xrandr --output DP-1 --primary
# Clipboard manager
exec-once = clipse -listen
