# Extra autostart processes
# exec-once = uwsm app -- my-service


# set mouse on workspace 1
# exec-once = hyprctl dispatch workspace 1
# exec-once = hyprctl dispatch movecurrentworkspacetomonitor DP-1

# Clipboard manager
exec-once = clipse -listen

